Repository opacity/webinterface, pull requests merged in 2020-03, with the labels that each got.

#366 Account upgrading
  config/paths.js
  config/webpack.config.js
  package-lock.json
  package.json
  src/components/file-manager/file-manager-slide.tsx
  src/components/shared/phases.tsx
  src/components/shared/subscriptions.tsx
  src/components/signup/breadcrumbs.tsx
  src/components/signup/confirm-payment-slide.tsx
  src/components/signup/create-account.tsx
  src/components/signup/crypto-payment.tsx
  src/components/signup/index.ts
  src/components/signup/invoice.tsx
  src/components/signup/phases.tsx
  src/components/signup/redeem.tsx
  src/components/signup/select-plan-slide.tsx
  src/components/signup/signup-flow.tsx
  src/components/signup/signup.tsx
  src/components/signup/thank-you.tsx
  src/components/signup/upgrade-account.tsx
  src/components/signup/upgrade.tsx
  src/config/index.ts
  src/index.tsx
  src/redux/actions/upgrade-actions.test.js
  src/redux/actions/upgrade-actions.ts
  src/redux/epics/index.ts
  src/redux/epics/upgrade-epic.test.js
  src/redux/epics/upgrade-epic.ts
  src/redux/reducers/index.ts
  src/redux/reducers/upgrade-reducer.test.js
  src/redux/reducers/upgrade-reducer.ts
Labels: enhancement

#367 Formatting and text changes
  src/components/file-manager/breadcrumbs.tsx
  src/components/file-manager/file-manager-slide.tsx
  src/redux/epics/file-epic.ts
Labels: bug

#368 Formatting and copy changes
  src/components/login/login-slide.tsx
  src/components/signup/crypto-payment.tsx
  src/components/signup/phases.tsx
  src/components/signup/record-recovery-phrase-slide.tsx
  src/components/signup/signup-flow.tsx
  src/components/signup/thank-you.tsx
Labels: frontend

#370 Homepage updates
  .DS_Store
  src/.DS_Store
  src/assets/.DS_Store
  src/assets/images/XIO.png
  src/assets/images/roadmap.png
  src/assets/images/roadmap2019.png
  src/components/landing-page/landing-page-slide.tsx
Labels: frontend
